const express=require('express')
const mongoose=require('mongoose');
const StatsSchema=new mongoose.Schema({
    Name:{
        type:String
    },
    orignal_name:{
        type:String
    },
    Runs:[
        {
            test:{
                type:String
            },
            odi:{
                type:String
            },
            t20:{
                type:String
            }
        }
    ],
    wickets:[
        {
            test:{
                type:String
            },
            odi:{
                type:String
            },
            t20:{
                type:String
            }
        }
    ],
    batting_average:[
        {
            test:{
                type:String
            },
            odi:{
                type:String
            },
            t20:{
                type:String
            }
        }
    ],
    bolwing_average:[
        {
            test:{
                type:String
            },
            odi:{
                type:String
            },
            t20:{
                type:String
            }
        }
    ]
    
})
module.exports=mongoose.model("stats",StatsSchema)